### ISSUE TITLE
Hi pavan

### ISSUE THREAD

**Issue by nani554** [boro741/FCC-Productivity-Challenge-Timer#1]
Hi pavan add me as a contributor and lets discuss about our project

**Comment by boro741** [comment]
Hey ur already a collaborator.
We were discussing on gitter last night. I was hoping u would joined yesterday.

https://gitter.im/FCC-Productivity-Challenge-Timer/Lobby

So I guess u know what our project is about. I want u to give ur opinion on features u would like to add.
